version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - spawnia
  assignees:
  - spawnia
  versioning-strategy: increase
  ignore:
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.78
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
    - 0.12.84
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.3
  - dependency-name: symfony/var-dumper
    versions:
    - 5.2.4
    - 5.2.5
